version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.32
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=reward
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  cache:
    image: redis:7.0.8
    restart: always
    ports:
      - 6379:6379
    command: redis-server --loglevel warning
    volumes:
      - cache:/data
  app:
    depends_on:
      - mysqldb
      - cache
    build: .
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/reward?allowPublicKeyRetrieval=true&useSSL=false",
            "spring.datasource.driverClassName" : "com.mysql.cj.jdbc.Driver",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "root",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
            "spring.jpa.hibernate.ddl-auto" : "update",
            "spring.jpa.show-sql" : "true",
            "redis.host" : "localhost",
            "redis.port" : "6379"
          }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
  cache:
    driver: local